/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Tier = IDL.Record({
  'quantity' : IDL.Int,
  'totalPrice' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'sku' : IDL.Opt(IDL.Text),
  'tiers' : IDL.Vec(Tier),
  'name' : IDL.Text,
  'createdAt' : Time,
  'unit' : IDL.Text,
  'updatedAt' : Time,
  'stock' : IDL.Int,
  'photo' : IDL.Opt(ExternalBlob),
  'price' : IDL.Nat,
});
export const CartItem = IDL.Record({
  'lineTotal' : IDL.Nat,
  'productId' : IDL.Nat,
  'quantity' : IDL.Int,
  'unitPrice' : IDL.Nat,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'cashReceived' : IDL.Nat,
  'paymentMethod' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'timestamp' : Time,
  'change' : IDL.Nat,
  'items' : IDL.Vec(CartItem),
});
export const Cart = IDL.Record({
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(CartItem),
});
export const StoreSettings = IDL.Record({
  'receiptFooter' : IDL.Opt(IDL.Text),
  'storeName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addOrUpdateProduct' : IDL.Func(
      [
        IDL.Opt(IDL.Nat),
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Nat,
        IDL.Int,
        IDL.Vec(Tier),
        IDL.Opt(ExternalBlob),
      ],
      [IDL.Nat],
      [],
    ),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Int], [], []),
  'checkout' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllSalesReports' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getCurrentCart' : IDL.Func([], [IDL.Opt(Cart)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getStoreSettings' : IDL.Func([], [StoreSettings], ['query']),
  'updateStoreSettings' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Tier = IDL.Record({ 'quantity' : IDL.Int, 'totalPrice' : IDL.Nat });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'sku' : IDL.Opt(IDL.Text),
    'tiers' : IDL.Vec(Tier),
    'name' : IDL.Text,
    'createdAt' : Time,
    'unit' : IDL.Text,
    'updatedAt' : Time,
    'stock' : IDL.Int,
    'photo' : IDL.Opt(ExternalBlob),
    'price' : IDL.Nat,
  });
  const CartItem = IDL.Record({
    'lineTotal' : IDL.Nat,
    'productId' : IDL.Nat,
    'quantity' : IDL.Int,
    'unitPrice' : IDL.Nat,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'cashReceived' : IDL.Nat,
    'paymentMethod' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'timestamp' : Time,
    'change' : IDL.Nat,
    'items' : IDL.Vec(CartItem),
  });
  const Cart = IDL.Record({
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(CartItem),
  });
  const StoreSettings = IDL.Record({
    'receiptFooter' : IDL.Opt(IDL.Text),
    'storeName' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addOrUpdateProduct' : IDL.Func(
        [
          IDL.Opt(IDL.Nat),
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Nat,
          IDL.Int,
          IDL.Vec(Tier),
          IDL.Opt(ExternalBlob),
        ],
        [IDL.Nat],
        [],
      ),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Int], [], []),
    'checkout' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllSalesReports' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getCurrentCart' : IDL.Func([], [IDL.Opt(Cart)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getStoreSettings' : IDL.Func([], [StoreSettings], ['query']),
    'updateStoreSettings' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };