/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cart { 'totalAmount' : bigint, 'items' : Array<CartItem> }
export interface CartItem {
  'lineTotal' : bigint,
  'productId' : bigint,
  'quantity' : bigint,
  'unitPrice' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Product {
  'id' : bigint,
  'sku' : [] | [string],
  'tiers' : Array<Tier>,
  'name' : string,
  'createdAt' : Time,
  'unit' : string,
  'updatedAt' : Time,
  'stock' : bigint,
  'photo' : [] | [ExternalBlob],
  'price' : bigint,
}
export interface StoreSettings {
  'receiptFooter' : [] | [string],
  'storeName' : string,
}
export interface Tier { 'quantity' : bigint, 'totalPrice' : bigint }
export type Time = bigint;
export interface Transaction {
  'id' : bigint,
  'cashReceived' : bigint,
  'paymentMethod' : string,
  'totalAmount' : bigint,
  'timestamp' : Time,
  'change' : bigint,
  'items' : Array<CartItem>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addOrUpdateProduct' : ActorMethod<
    [
      [] | [bigint],
      string,
      [] | [string],
      string,
      bigint,
      bigint,
      Array<Tier>,
      [] | [ExternalBlob],
    ],
    bigint
  >,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'checkout' : ActorMethod<[string, bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllSalesReports' : ActorMethod<[], Array<Transaction>>,
  'getCurrentCart' : ActorMethod<[], [] | [Cart]>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getStoreSettings' : ActorMethod<[], StoreSettings>,
  'updateStoreSettings' : ActorMethod<[string, [] | [string]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];